---
name: Check patch
permissions:
  pull-requests: read
  contents: read

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream
          - name: centos-stream-10
            shortcut: cs10
            container-name: el10stream

    env:
      ARTIFACTS_DIR: exported-artifacts

    name: ${{ matrix.name }}

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
      - name: prepare env
        if: ${{ matrix.shortcut == 'cs9' }}
        run: |
            dnf install -y --setopt=tsflags=nodocs git rpmlint glibc-langpack-en

      - name: prepare env
        if: ${{ matrix.shortcut == 'cs10' }}
        run: |
          dnf install -y epel-release
          dnf install -y rpmlint
          dnf config-manager --set-disable epel
          dnf install -y --setopt=tsflags=nodocs git glibc-langpack-en

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run rpmlint
        run: LC_ALL=en_US.UTF-8 rpmlint ovirt-host.spec

      - name: Build RPM
        run: |
          mkdir -p tmp.repos/SOURCES
          cp LICENSE tmp.repos/SOURCES
          rpmbuild -D "_topdir ${PWD}/tmp.repos" -D "release_suffix .$(date -u +%Y%m%d%H%M%S).git$(git rev-parse --short HEAD)" -ba ovirt-host.spec

      - name: Collect artifacts
        run: |
            mkdir -p exported-artifacts
            find tmp.repos -iname \*rpm -exec mv "{}" exported-artifacts/ \;

      - name: Test install
        run: |
            yum --downloadonly install -y exported-artifacts/*x86_64.rpm

      - name: Upload RPMs
        uses: ovirt/upload-rpms-action@main
        with:
          directory: ${{ env.ARTIFACTS_DIR }}
